### ISSUE TITLE
Ambioder with new SC91F729BM?

### ISSUE THREAD

**Issue by TASSDevon** [Gabriel-LG/Ambioder#2]
Hi,

I went out to buy a Dioder because I wanted to try your Ambioder project at home as well. As the other Dioder project page says, the new chip is a SC91F729BM which replaced the microchip. Have you played around with it by chance? I can't seem to find anything on the net about it.

**Comment by Gabriel-LG** [comment]
Hi Devon,

Thank you for your interest in Ambioder. I have gotten another report of
the Dioder microcontroller being replaced.
I have not yet looked at this microcontroller. However porting Ambioder to
another CPU architecture would mean rewriting it in total, which I was not
planning to do.
I will add an update to the project page to warn about this.

kind regards,
Lambertus

**Comment by TASSDevon** [comment]
Alright, figured it wouldn't be that easy especially since the only documentation for the chip is a Chinese datasheet. It's a good thing Ikea is very lenient on returns :) Thanks for the reply though!
